# Precompile directives generated by SnoopCompile
# Regenerate with: mpiexec -n 1 julia --project=. scripts/generate_precompile.jl
#
# 35 method instances

function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{typeof(ldlt),SparseMatrixMPI{Float64}})   # time: 0.94416517
    Base.precompile(Tuple{typeof(+),SparseMatrixMPI{Float64},SparseMatrixMPI{Float64}})   # time: 0.7049556
    Base.precompile(Tuple{typeof(+),VectorMPI{Float64},VectorMPI{Float64}})   # time: 0.52260745
    Base.precompile(Tuple{typeof(blockdiag),SparseMatrixMPI{Float64},Vararg{SparseMatrixMPI{Float64}}})   # time: 0.5169769
    Base.precompile(Tuple{typeof(*),SparseMatrixMPI{Float64},MatrixMPI{Float64}})   # time: 0.38069284
    Base.precompile(Tuple{typeof(norm),VectorMPI{Float64}})   # time: 0.32113355
    Base.precompile(Tuple{typeof(*),MatrixMPI{Float64},VectorMPI{Float64}})   # time: 0.29184937
    let fbody = try Base.bodyfunction(which(cat, (VectorMPI{Float64},Vararg{VectorMPI{Float64}},))) catch missing end
    if !ismissing(fbody)
        precompile(fbody, (Int64,typeof(cat),VectorMPI{Float64},Vararg{VectorMPI{Float64}},))
    end
end   # time: 0.2741604
    Base.precompile(Tuple{typeof(*),SparseMatrixMPI{Float64},SparseMatrixMPI{Float64}})   # time: 0.22065157
    Base.precompile(Tuple{typeof(norm),MatrixMPI{Float64}})   # time: 0.11287689
    Base.precompile(Tuple{typeof(\),MUMPSFactorizationMPI{Float64},VectorMPI{Float64}})   # time: 0.10963011
    Base.precompile(Tuple{typeof(get_dense_transpose_plan),MatrixMPI{Float64}})   # time: 0.09276378
    Base.precompile(Tuple{typeof(-),SparseMatrixMPI{Float64},SparseMatrixMPI{Float64}})   # time: 0.08869523
    Base.precompile(Tuple{typeof(*),Float64,MatrixMPI{Float64}})   # time: 0.08400875
    Base.precompile(Tuple{typeof(execute_plan!),TransposePlan{Float64},SparseMatrixMPI{Float64}})   # time: 0.066327214
    Base.precompile(Tuple{typeof(norm),SparseMatrixMPI{Float64}})   # time: 0.058926105
    Base.precompile(Tuple{typeof(-),VectorMPI{Float64},VectorMPI{Float64}})   # time: 0.0568527
    Base.precompile(Tuple{typeof(*),VectorMPI{Float64},Float64})   # time: 0.04577881
    Base.precompile(Tuple{typeof(execute_plan!),DenseTransposePlan{Float64},MatrixMPI{Float64}})   # time: 0.03494811
    Base.precompile(Tuple{typeof(conj),VectorMPI{Float64}})   # time: 0.029460788
    Base.precompile(Tuple{typeof(clear_plan_cache!)})   # time: 0.020269096
    Base.precompile(Tuple{typeof(getindex),SparseMatrixMPI{Float64},Int64,Int64})   # time: 0.018534482
    Base.precompile(Tuple{typeof(*),SparseMatrixMPI{Float64},Float64})   # time: 0.0153384805
    Base.precompile(Tuple{typeof(getindex),VectorMPI{Float64},Int64})   # time: 0.008301735
    Base.precompile(Tuple{typeof(getindex),MatrixMPI{Float64},Int64,Int64})   # time: 0.008245468
    Base.precompile(Tuple{typeof(nnz),SparseMatrixMPI{Float64}})   # time: 0.006911695
    Base.precompile(Tuple{typeof(uniform_partition),Int64,Int64})   # time: 0.0067830086
    Base.precompile(Tuple{typeof(dot),VectorMPI{Float64},VectorMPI{Float64}})   # time: 0.006173551
    Base.precompile(Tuple{typeof(finalize!),MUMPSFactorizationMPI{Float64}})   # time: 0.00417161
    Base.precompile(Tuple{typeof(size),SparseMatrixMPI{Float64}})   # time: 0.002782762
    Base.precompile(Tuple{typeof(transpose),MatrixMPI{Float64}})   # time: 0.0018849373
    Base.precompile(Tuple{typeof(transpose),SparseMatrixMPI{Float64}})   # time: 0.0018328428
    Base.precompile(Tuple{typeof(size),VectorMPI{Float64}})   # time: 0.001739502
end

_precompile_()
